# Generated by Django 3.2.4 on 2021-07-03 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210701_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 10, 54, 58, 381873, tzinfo=utc)),
        ),
    ]
